# Import nodejs from docker hub
FROM node:14-alpine As build
ENV NODE_ENV production
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . ./
RUN npm run build


FROM nginx
COPY --from=build /app/build /usr/share/nginx/html