version: "3.8"

services: 
  app:
    container_name: app_dev
    image: app_dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment: 
      - REACT_APP_NAME:YASH-DEV