version: "3.8"

services: 
  app:
    container_name: app_prod
    image: app_prod
    build: 
      context: .
      dockerfile: Dockerfile.prod 
    environment: 
      - REACT_APP_NAME=YASH-PROD

  
